9.2task
TaQba/kodilla-course pull request #21
Opened 2018-11-30 17:17 UTC by TaQba

Zdaje sobie sprawę ze przekombinowalem.

Nie chce juz podchodzić  do tego tasku, bo za dużo czasu zainwestowałem w ten program. Mam nadzieje ze znajdziesz powody by to zaakceptować. ;)

2018-11-30 21:03 UTC, MichalOrlowski requested changes

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/httpClient.java
> +public class httpClient implements ClientInterface {
nazwy klas w Javie z wielkiej litery

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/AllegroService.java
> +            if (this.search(product.toString())) {
wg mnie lepiej gdyby Product mial pole `productName`, wtedy unikiniemy toStringa

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/IShopInterface.java
> +interface IShopInterface {
ClientInterface i IShopInterface - mają podobne metody. Spróbowałbym to uwspólnić

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Orders.java
> +        for(Map.Entry<Product, String> entry :ordersMap.entrySet()){
niesformatowany kod (ctrl + alt + l) w intellij

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Product.java
> +    String name;
zmienna powinna być private

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/Product.java
> +public class Product extends Object {
extends Object - jest niepotrzebne w Javie

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/ProductException.java
> +public class ProductException extends Exception {
dobrze by było nadpisać metody klasy Exception, tak żeby message był customowy (np. Product does not exist).

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/ProductList.java
> +    public static ArrayList get() {
Tutaj mamy lekki rozjazd - klasa nazywa się ProductLIst, a metoda get. 
Proponowałbym klasę nazwać bardziej domenowo, a metodę getProductList.

2018-11-30 21:03 UTC, MichalOrlowski commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/IShopInterface.java
> +interface IShopInterface {
nazywanie interface z prefixem "I" jest bardzo starą praktyką

2018-12-01 10:17 UTC, merged

2018-12-01 10:18 UTC, TaQba commented
ok