Task 20.2
TaQba/kodilla-course pull request #25
Opened 2018-12-09 11:48 UTC by TaQba

2018-12-09 12:20 UTC, MichalOrlowski requested changes

2018-12-09 12:20 UTC, MichalOrlowski commented on kodilla-spring/src/test/java/com/kodilla/spring/calculator/CalculatorTestSuite.java
> +        //do nothing
sprawdz czy wynik jest poprawny, masz dostep do display

2018-12-09 12:42 UTC, TaQba commented on kodilla-spring/src/test/java/com/kodilla/spring/calculator/CalculatorTestSuite.java
> +        //do nothing
Applied

2018-12-11 20:30 UTC, MichalOrlowski approved these changes

2018-12-12 19:16 UTC, merged